version: '3'
services:
  quest1:
    build: 
      context: ./
      dockerfile: ./chapters/quest1/Dockerfile
    ports:
      - "3000"
    command: ["./start_app.sh"]
    volumes:
      - ./node:/app/node
      - ./chapters:/app/chapters
    environment:
      CHAPTER: "quest1"

  client_server:
    build: 
      context: ./
      dockerfile: ./chapters/client_server/Dockerfile
    ports:
      - "3000"
    command: ["./start_app.sh"]
    volumes:
      - ./node:/app/node
      - ./chapters:/app/chapters
    environment:
      CHAPTER: "client_server"

  nginx:
    build: ./compose/nginx/dev/
    ports:
      - "8000:80"

  auth:
    build: ./authenticator/
    volumes:
      - ./authenticator:/app
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8888"
    command: ["./start_app.sh"]

  db:
    image: postgres:9.6
    environment:
      POSTGRES_PASSWORD: awesomesauce
      POSTGRES_DB: wetty
    ports:
      - "5432:5432"
