version: '2'
services:
  web:
    build: .
    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8888:8888"
    command: "./start_app.sh"
  db:
    image: postgres:9.6
    environment:
      POSTGRES_PASSWORD: awesomesauce
      POSTGRES_DB: wetty
    ports:
      - "5432:5432"

